### ISSUE TITLE
HTTP-Statuscode 401. Not Authorized

### ISSUE THREAD

**Issue by ibiBgOR** [giorger/python-runtastic#3]
Hey there. I'm tried to use this library. First: Thanks for translating from php to python (as far as i saw it :D )
The code I'm using to connect to runtastic is:

```
myConnection = runtastic.Runtastic()
mySessionId = myConnection.login('')
myConnection.retrieve_all_sessions(mySessionId)

print myConnection.all_sport_sessions

myConnection.logout(mySessionId)
```

So far so good. But I always get '{}' as result. After reviewing the code and making some prints into the code I was able to figure out that this:

```
self.runtastic_response = self.runtastic_connection.submit_request(self.config.RUNTASTIC_URL_SPORT_SESSION,
                                                                               (Runtastic.__sessions[session_uuid])
                                                                               [self.config.RUNTASTIC_FLD_USERNAME])
```

might be the place where I get the 401 Unauthorized. I took a look into the response text and it says that I'm not logged in. At another place in the code (don't know exactly where it was) I have seen that my result is empty because of my runtastic privacy settings (disabled access from anyone). But I thought that if I login with my credentials I would be able to see my data.

Do you have any idea how to get my data?

Have a nice evening.

**Comment by giorger** [comment]
Hello,

Have you set properly the below values in python-runtastic.ini ?

`[runtastic-user-settings]`
`userName = user@email.com`
`userPassword = password`

Judging by the error you are reporting regarding not logged in, i think that provided credentials might not be proper.
If credentials are proper, please let me know so we can troubleshoot together (first step would be to inject before line 212 the following 
`self.runtastic_response_json['current_user']['slug']` and check in the output if your username is properly printed).

Regards,
Giorgos

**Comment by ibiBgOR** [comment]
Ok I just copied the code from the files here in my project. There are some things that already are not working out of the box (at least for me.):
- IOError: [Errno 2] No such file or directory: 'python-runtastic.ini'
  - fixed with `import os` and `
      self.config = ConfigurationObject(os.path.join(os.path.dirname(__file__), "python-runtastic.ini"))` in line 164
- ConfigParser.NoOptionError: No option 'sportsessionurl' in section: 'runtastic'
  - fixed with renaming the param `sportSessionURL_Sport` to `sportSessionURL` in the ini file

After "fixing" these errors and running only this file (python python_runtastic.py) I get an error (httplib.ResponseNotReady) in `File "lib/python_runtastic.py", line 226, in logout
  self.runtastic_response = self.runtastic_connection.submit_request(self.config.RUNTASTIC_URL_LOGOUT)`
I figured out ([I love stackoverflow](http://stackoverflow.com/questions/3231543/python-httplib-responsenotready)) that I just need to rebuild the connection. After this my (slightly modified) console output looks like: 

```
Result status not 200 but: 401
None
Signed out
```

I doublechecked my credentials! The output of `print 'slug: ' + self.runtastic_response_json['current_user']['slug']` seams correct! its <first letter first name>-<first letter surname>-<mail without @ and following>

**Comment by ibiBgOR** [comment]
Any idea?

**Comment by giorger** [comment]
Excuse my delay, i had missed this :S. Will check and let you know

Managed to reproduce it, only outside my dev environment :s but not to resolve it. will ping you

**Comment by giorger** [comment]
There is something wrong with cookies i think. When using cookies i get response code 200 but the message is still access denied.
Investigating

**Comment by giorger** [comment]
@ibiBgOR: Should be ok now. Please get updated files from Repo and try again. 
Technically, 
- Cookies were missing thus the access denial errors. Fixed
- httplib has been replaces by requests lib. Not cause of the issue, but requests is easier to work with.
- Typos in ".ini". Thank you for pointing out, also Fixed.

**Comment by ibiBgOR** [comment]
Dude! You are genius! It seem to work perfectly. I tried the new files and retrived my running sessions :+1:
